name: some-app
recipe: drupal8
config:
  webroot: web
services:
  appserver:
    build:
      - composer install
      - drush sql-drop -y && drush sqlc < drupal.sql
      - drush cim -y
      - drush cr
