name: some-app
recipe: drupal8
config:
  webroot: web
  database: mysql:5.7.24
services:
  appserver:
    build:
      - composer install
events:
  post-start:
    - echo "Database import started"
    - drush sqlc < drupal.sql
    # - drush cim -y
    - drush cr
